package com.epicest.snippetmanager.gui;

import java.awt.Desktop;
import java.net.URL;
import javax.swing.JFrame;

/**
 * A simple about window, nothing really functional
 *
 * @author Jayar
 */
public class AboutFrame extends javax.swing.JFrame {

 /**
  * Creates new form AboutFrame
  *
  * @param relativeLocation the parent frame to be placed over
  */
 public AboutFrame(JFrame relativeLocation) {
  initComponents();
  setLocationRelativeTo(relativeLocation);
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  titleLabel = new javax.swing.JLabel();
  jScrollPane1 = new javax.swing.JScrollPane();
  aboutTextArea = new javax.swing.JTextArea();
  okButton = new javax.swing.JButton();

  setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
  setTitle("About Program");

  titleLabel.setFont(new java.awt.Font("Source Code Pro", 0, 36)); // NOI18N
  titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  titleLabel.setText("Snippet Manager");

  aboutTextArea.setEditable(false);
  aboutTextArea.setColumns(20);
  aboutTextArea.setLineWrap(true);
  aboutTextArea.setRows(5);
  aboutTextArea.setText("Pixelcraft Snippet Manager was created by EpicestGamer\nYou can contact him at epicestgamersbots@gmail.com\n\nPixelcraft Snippet Manager was first made to sort useful code tidbits, but upon further analysis, it was found that it could easily be adapted to other forms of information. Whether you're creating characters or just taking notes, this program can do it and keep you sorted.");
  aboutTextArea.setWrapStyleWord(true);
  jScrollPane1.setViewportView(aboutTextArea);

  okButton.setText("Ok");
  okButton.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    okButtonActionPerformed(evt);
   }
  });

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addContainerGap()
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
      .addGap(0, 0, Short.MAX_VALUE)
      .addComponent(okButton))
     .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    .addContainerGap())
  );
  layout.setVerticalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(titleLabel)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addComponent(okButton)
    .addContainerGap())
  );

  pack();
 }// </editor-fold>//GEN-END:initComponents

 /**
  * Closes the window
  */
 private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
  this.dispose();
 }//GEN-LAST:event_okButtonActionPerformed

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JTextArea aboutTextArea;
 private javax.swing.JScrollPane jScrollPane1;
 private javax.swing.JButton okButton;
 private javax.swing.JLabel titleLabel;
 // End of variables declaration//GEN-END:variables
}
